# Generated by Django 3.1.4 on 2020-12-31 19:08

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201229_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email already in use.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Username already in use.'}, help_text='Required. 32 characters or fewer. Letters, digits and _ only.', max_length=32, unique=True, validators=[users.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
